export enum AuthAction {
  LOGIN = "LOGIN",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILED = "LOGOUT_FAILED",
  REGISTER = "REGISTER",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAILED = "REGISTER_FAILED",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED",
  RESET_PASSWORD = "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED",
  LOGIN_MULTI_FACTOR = "LOGIN_MULTI_FACTOR",
  LOGIN_MULTI_FACTOR_SUCCESS = "LOGIN_MULTI_FACTOR_SUCCESS",
  LOGIN_MULTI_FACTOR_FAILED = "LOGIN_MULTI_FACTOR_FAILED",
  LOADING = "LOADING",
  UPDATE_PASSWORD = "UPDATE_PASSWORD",
  UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED",
  SEND_EMAIL_VERIFICATION = "SEND_EMAIL_VERIFICATION",
  SEND_EMAIL_VERIFICATION_SUCCESS = "SEND_EMAIL_VERIFICATION_SUCCESS",
  SEND_EMAIL_VERIFICATION_FAILED = "SEND_EMAIL_VERIFICATION_FAILED",
  SEND_MAGIC_LINK = "SEND_MAGIC_LINK",
  SEND_MAGIC_LINK_SUCCESS = "SEND_MAGIC_LINK_SUCCESS",
  SEND_MAGIC_LINK_FAILED = "SEND_MAGIC_LINK_FAILED",
}

export enum HomeAction {
  GET_DATA = "GET_DATA",
  GET_DATA_SUCCESS = "GET_DATA_SUCCESS",
  GET_DATA_FAILED = "GET_DATA_FAILED",
  ADD_COUNTRY = "ADD_COUNTRY",
  ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS",
  ADD_COUNTRY_FAILED = "ADD_COUNTRY_FAILED",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED",
  UPGRADE_PROFILE = "UPGRADE_PROFILE",
  UPGRADE_PROFILE_SUCCESS = "UPGRADE_PROFILE_SUCCESS",
  UPGRADE_PROFILE_FAILED = "UPGRADE_PROFILE_FAILED",
  UPLOAD_IMAGE = "UPLOAD_IMAGE",
  UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED",
  UPLOAD_FILE = "UPLOAD_FILE",
  UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED",
  GET_USERS = "GET_USERS",
  GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
  GET_USERS_FAILED = "GET_USERS_FAILED",
  POST_DOCUMENT = "POST_DOCUMENT",
  POST_DOCUMENT_SUCCESS = "POST_DOCUMENT_SUCCESS",
  POST_DOCUMENT_FAILED = "POST_DOCUMENT_FAILED",
  CONFIRM_DOCUMENT = "CONFIRM_DOCUMENT",
  CONFIRM_DOCUMENT_SUCCESS = "CONFIRM_DOCUMENT_SUCCESS",
  CONFIRM_DOCUMENT_FAILED = "CONFIRM_DOCUMENT_FAILED",
  GET_ME = "GET_ME",
  GET_ME_SUCCESS = "GET_ME_SUCCESS",
  GET_ME_FAILED = "GET_ME_FAILED",
  GET_COUNTRIES = "GET_COUNTRIES",
  GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAILED = "GET_COUNTRIES_FAILED",
}

export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
}

export enum MARITAL_STATUS {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
}

export enum Gender {
  MAN = "MAN",
  WOMAN = "WOMAN",
  OTHER = "OTHER",
}

export enum Status {
  UNVERIFIED = "UNVERIFIED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  VERIFIED = "VERIFIED",
}

export enum DOCUMENT_NAME {
  PASSPORT = "PASSPORT",
  NATIONAL_ID = "NATIONAL_ID",
}
